version: '3'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    container_name: nodeapp
    ports:
      - "80:8080"
    volumes:
      # Bind mount for the app directory, could use environment variable to make this sturdier
      - .:/usr/src/app
      # Assumes the the host doesn't have a pre-existing nod_modules directory
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
